// <auto-generated />
using System;
using ENROLLMENTSYSTEMBACKEND.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENROLLMENTSYSTEMBACKEND.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class EnrollmentInformationModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Basic model configuration
            modelBuilder.Entity("ENROLLMENTSYSTEMBACKEND.Models.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("ENROLLMENTSYSTEMBACKEND.Models.UserLog", b =>
            {
                b.Property<int>("UserLogId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLogId"));

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("EmailAddress")
                    .IsRequired()
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("UserLogTimeStamp")
                    .HasColumnType("datetime2");

                b.Property<string>("UserLogActivity")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserProfileImagePath")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserLogId");

                b.HasIndex("UserId");

                b.ToTable("UserLogs");
            });

            modelBuilder.Entity("ENROLLMENTSYSTEMBACKEND.Models.UserLog", b =>
            {
                b.HasOne("ENROLLMENTSYSTEMBACKEND.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });
        }
    }
}